version: "3.4"
services:
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    networks:
    - tracing
    ports:
    - 16686:16686
    - 14269:14269
    - 5775:5775/udp
    - 6831:6831/udp
    - 6832:6832/udp
    - 5778:5778
    - 14268:14268
    - 9411:9411 

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - 3000:3000
networks: 
  tracing:
    name: tracing
